### ISSUE TITLE
 ERROR 'ascii' codec can't decode byte 0x82

### ISSUE THREAD

**Issue by reset12** [nrocco/smeterd#17]
I tried smeterd now with the following parameters:
smeterd -v read-meter --serial-port /dev/ttyUSB0 --serial-baudrate 9600 --serial-bytesize 8 --serial-parity N --serial-stopbits 1
[2016-12-12 21:50:12,761] INFO New serial connection opened to /dev/ttyUSB0
[2016-12-12 21:50:12,766] INFO Start reading lines
[2016-12-12 21:50:14,826] ERROR 'ascii' codec can't decode byte 0x82 in position 2: ordinal not in range(128)
[2016-12-12 21:50:14,830] ERROR Read a total of 1 lines
[2016-12-12 21:50:14,838] INFO Closing connection to `/dev/ttyUSB0`.
Traceback (most recent call last):
  File "/usr/local/bin/smeterd", line 11, in <module>
    load_entry_point('smeterd==2.7.1', 'console_scripts', 'smeterd')()
  File "build/bdist.linux-armv6l/egg/smeterd/cli/__init__.py", line 22, in parse_and_run
  File "build/bdist.linux-armv6l/egg/smeterd/cli/read_meter.py", line 64, in run
  File "build/bdist.linux-armv6l/egg/smeterd/meter.py", line 76, in read_one_packet
smeterd.meter.SmartMeterError: 'ascii' codec can't decode byte 0x82 in position 2: ordinal not in range(128)

I have the following smartmeter: http://wiki.volkszaehler.org/hardware/channels/meters/power/edl-ehz/emh-ehz-h1

with regards
Bruno

**Comment by ThinkPadNL** [comment]
I'm not the author of this repository, but:
The code posted in this repository is for Dutch smart meters, following the DSMR output. Your meter seems very different, and thus, probably won't work with the code from this repository.
